[id]
name = vhc_TA_csmon
version = 1.0.1

[ui]
is_visible = true
label = CSmon®
supported_themes = light, dark

[launcher]
author = Ing. Victor Hasler, MSc
description = SAP® Monitoring mit CSmon®
version = 1.0.1

[package]
check_for_updates = true
id = vhc_TA_csmon

[install]
is_configured = false
build = 1773269866
state = enabled

[triggers]
reload.splunk_create = simple
reload.vhc_ta_csmon_settings = simple
