[csmon_index]
definition = index=[| rest splunk_server=local /servicesNS/-/-/configs/conf-vhc_ta_csmon_settings/settings | search title="settings" | return $index]

[csmon_sap_systems]
definition = [| rest splunk_server=local /servicesNS/-/-/configs/conf-vhc_ta_csmon_settings/system_settings | search title="system_settings" | return $sap_systems]

[csmon_hana_systems]
definition = [| rest splunk_server=local /servicesNS/-/-/configs/conf-vhc_ta_csmon_settings/system_settings | search title="system_settings" | return $hana_systems]

[csmon_perf_data]
definition = \
    | spath output=serviceperfdata path=SERVICEPERFDATA{} \
    | mvexpand serviceperfdata \
    | spath input=serviceperfdata output=critical path=critical \
    | spath input=serviceperfdata output=label path=label \
    | spath input=serviceperfdata output=max path=max \
    | spath input=serviceperfdata output=min path=min \
    | spath input=serviceperfdata output=uom path=uom \
    | spath input=serviceperfdata output=value path=value \
    | spath input=serviceperfdata output=warning path=warning

