[admin:vhc_TA_csmon_configuration]
match = /
members = vhc_TA_csmon_settings

[admin_external:vhc_TA_csmon_settings]
handlertype = python
python.version = python3
handlerfile = vhc_TA_csmon_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true
